name: Update Credits

on: push

jobs:
  update-credits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Update credits
        shell: bash
        run: |
            chmod +x ./bin/gtool && ./bin/gtool -L graph
      - name: Update credits
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "credits: update credits"
